#import "../diagrams.typ": graphical-abstract

= Introduction

Consider a prospective student typing into a chat interface in Spanish: #emph[¿qué diferencia hay entre el grado en Inteligencia Artificial y el de Ingeniería Informática?] -- what is the difference between the AI bachelor and the Computer Engineering bachelor? The answer exists. It is split across two program pages on a university website, each with frontmatter that fixes the exact number of ECTS credits, the modality, the start date, the language of instruction, and a year-by-year curriculum. The institution publishes this information as the source of truth for student decisions. The student would like a direct answer, with citations to those pages, in Spanish, in under twenty seconds.

This is the regime the LaSalle Wiki Tutor is built for. The institution it advises is La Salle Campus Barcelona, a faculty of Universitat Ramon Llull, with a bilingual academic catalog of 357 program records and 4{,}606 subject records spread across an English and a Spanish web tree. The scale matters: the catalog is too large to fit into any reasonable prompt, and too small to repay the operational machinery of a managed vector database with its index lifecycle, embedding drift, and serving overhead. It is also too high-stakes for the failure modes that come with naive retrieval-augmented generation: a wrong ECTS count, a hallucinated faculty name, or a fabricated tuition figure damages the institution.

#figure(
  graphical-abstract,
  caption: [Graphical abstract. The system compiles the catalog once into a structured wiki, exposes ten deterministic read-only tools to a streaming agent, and confines vector retrieval to one tool. Answers cite the institution's own pages.],
) <fig:abstract>

@fig:abstract surveys the architecture this paper defends. Three design pressures shape what follows. First, #emph[bilingual symmetry]: every program may exist in English, in Spanish, in both, or in neither, and the system must answer fluently in whichever language the student wrote, with citations to the corresponding language's source page. Second, #emph[mid-scale knowledge]: the catalog is bounded, structured, and slowly changing; it does not call for the affordances of a vector database, but it does call for something more disciplined than putting the whole thing into a system prompt. Third, #emph[institutional cost of being wrong]: every claim must be grounded in the catalog or it must not be made at all.

The thesis of this paper is that for knowledge bases of this shape -- bounded, structured, slowly changing -- a curated and compiled Markdown wiki navigated by a small set of deterministic tools is a more honest substrate than the default chunk-and-embed retrieval pipeline. This argument is recognisably the #emph[LLM Wiki] pattern that @karpathy2026llmwiki articulated as a design proposal, grounded in the broader framing of large language models as an emerging operating system whose context window functions as scarce RAM @karpathy2025software3. It is also empirically defensible against the failure modes of naive retrieval-augmented generation @barnett2024sevenfailures and against the long-context degradation that the alternative of "stuff everything into the prompt" induces in even very capable models @liu2024lostinthemiddle @laban2025lostinconversation.

We do not reject vector retrieval as a primitive. We reject it as the agent's general substrate. Inside one tool -- the free-text `search_programs` -- the system runs a hybrid blend of BM25-F field-weighted lexical scoring @robertson2009bm25 and Model2Vec 256-dimensional static embeddings @tulkens2024model2vec, in the lineage of dense-retrieval methods @reimers2019sbert @karpukhin2020dpr, modulated by a small intent prior. Section 3 documents the precise blend. The remaining nine tools are deterministic file reads with structured arguments and structured returns. The agent navigates this surface using the tool-use lineage of @yao2023react and, in spirit, the selective-retrieval refinement of @asai2024selfrag, in which the model chooses #emph[when] to consult an external source rather than always doing so.

This paper makes four contributions. First, we document a field-targeted extraction pipeline that produces structured Markdown with strict YAML frontmatter from a Drupal-based university catalog, with a measured fallback rate of 1.6%. Second, we present a ten-tool surface that the system prompt bounds to at most five tool calls per response; the production trace store shows that catalog-shaped student questions typically resolve well below this ceiling (Section 5.3). Third, we present a hybrid retrieval design --- BM25-F + Model2Vec --- confined to a single tool, and we ablate it across four ranker modes on a 20-query benchmark. Fourth, we describe an observability-first runtime in which three MongoDB collections record reasoning passages, tool timings, and conversation metadata, supplying the empirical material this paper reports. The system runs publicly at #link("https://lasalle.generateeve.com"); the deployment recipe, access mechanism, and code-and-data availability statement are in Section 4.
