= Related Work

== Retrieval-augmented generation and its failure modes

The canonical formulation of retrieval-augmented generation pairs a dense retriever over a document collection with a generator conditioned on the retrieved passages @lewis2020rag, building on dense passage retrieval @karpukhin2020dpr and bi-encoder embedding methods @reimers2019sbert. The pattern is now the default reflex when an LLM application needs to ground its answers in external text. It is also empirically fragile. @barnett2024sevenfailures catalogues seven distinct failure modes in production RAG systems -- missing content, retrieval at the wrong granularity, top-K cutoffs, chunking-boundary information loss, generation drift, formatting drift, and version drift between the index and the source -- each of which is invisible at small evaluation scale and recurs in deployment. The LaSalle Wiki Tutor avoids the chunking-boundary and granularity classes by construction: there is no chunking. The retrieval surface is the wiki's natural unit (a program record, a subject record, a curriculum section), and the agent calls a deterministic tool to return it. The retrieval miss class is mitigated by the hybrid lexical-and-semantic blend inside `search_programs` (Section 3.5), the wider tool surface that lets the agent recover via `list_programs` or `get_index_facets` when free-text retrieval underperforms, and the structured frontmatter that gives the BM25-F scorer rich short-text fields to weigh.

@asai2024selfrag occupies an interesting position in this lineage: a refinement of RAG in which the model emits reflection tokens that decide when to retrieve, what to retrieve, and how to critique the retrieved evidence. The LaSalle Wiki Tutor is not Self-RAG, but it shares Self-RAG's premise that retrieval should be on-demand rather than always-on. The mechanism is different: where Self-RAG decides whether to retrieve at the token level, our system decides whether to retrieve at the tool-call level, and which structured tool to call. The point of contact is the recognition that always retrieving is not the right default.

== Long-context degradation and conversation drift

A naive alternative to RAG for a corpus of our size would be to inline the whole wiki into the system prompt. @liu2024lostinthemiddle measures the empirical cost of this strategy: even very capable language models lose accuracy when relevant facts sit in the middle of a long context, with a U-shaped curve that favours the beginning and the end of the window. The effect compounds in multi-turn conversation: @laban2025lostinconversation reports a roughly 39% performance drop in multi-turn settings versus single-turn baselines, attributed to a "loss of middle turns" in which the model effectively forgets information that arrived in earlier exchanges. Both findings argue against the conversation history being the primary substrate for catalog facts. The LaSalle Wiki Tutor responds to this evidence in two ways. We bound conversation history to the eight most recent runs via Agno's `num_history_runs=8`, and we have the agent re-fetch through tools on every turn rather than relying on the model's recall of earlier tool returns. The cost is a small extra tool call per turn; the benefit is that the answer is grounded in current frontmatter rather than in a possibly-stale recollection.

== Foundational retrieval and the case for BM25-F

The case for keeping a lexical scorer in the retrieval pipeline rests on a literature that predates large language models. Term-frequency-inverse-document-frequency weighting was formalised by @sparck1972idf and remains the analytical foundation of BM25, whose probabilistic-relevance derivation and field-weighted extension to BM25-F are documented authoritatively in @robertson2009bm25. For a corpus whose primary units are short and frontmatter-heavy -- a program record's title, tags, area, and level field together account for most of the discriminative signal -- a field-weighted lexical scorer is hard to beat with dense embeddings alone, and the ablation in Section 5.2 is consistent with this prior: the lexical-only mode wins top-1 by five points and ties hybrid at top-3. The role of the dense signal is at the tail: at top-5, hybrid reaches 100% only because the semantic branch catches the queries where literal-token overlap is zero.

== Static embeddings and the agent-tools lineage

The semantic pole in our retrieval pipeline is intentionally lightweight. Model2Vec @tulkens2024model2vec distils static word embeddings from a transformer-based sentence encoder, producing fixed-size per-token vectors that can be pooled into a sentence-level representation without a transformer pass at query time. The peer-reviewed counterpart to this approach is the static-word-embedding-for-sentence-representation line of work @wada2025staticembeddings, which characterises the design space (PCA on Sentence Transformer outputs, contrastive distillation) and shows that the resulting static embeddings approach the recall quality of their teachers at a fraction of the runtime cost. For our scale (357 programs, embeddings precomputed once at wiki-render time) the cost-quality balance lands cleanly: a 256-dimensional vector per program, a 180 kB `.npz` file per language, a numpy matrix-vector multiply per query.

The agent-tools half of the architecture is recognisable as the ReAct lineage @yao2023react, in which a language model interleaves reasoning steps and tool actions. The LaSalle Wiki Tutor is closer to a constrained ReAct than to the full Self-RAG-style critic loop: the model emits reasoning, picks a tool, reads the JSON return, and continues. The constraints are the system prompt's "at most five tool calls" budget and the read-only nature of the tool surface. There is no write tool, no critic loop, no plan-and-execute scaffolding.

== The design philosophy: the LLM Wiki

The non-peer-reviewed design proposal that most directly captures the architectural commitment we make is @karpathy2026llmwiki, which articulates the "LLM Wiki" pattern as a three-layer design: raw immutable sources, an LLM-curated wiki layer that synthesises them, and a schema document (the gist proposes `CLAUDE.md` or `AGENTS.md`) that governs structure and conventions. The design philosophy frames the wiki as a compiled, persistent artefact rather than a query-time synthesis, and it sits within @karpathy2025software3's broader "Software 3.0" framing in which LLMs are an emerging operating system with the context window functioning as scarce RAM. Both sources are non-peer-reviewed and we cite them as primary sources for the design philosophy under defence, not as evidence for our empirical claims; the evidential weight in this paper rests on the peer-reviewed work surveyed above.

The LaSalle Wiki Tutor differs from the LLM Wiki proposal in one important respect: the wiki in our system is built by a deterministic extraction pipeline from the institution's published catalog, not maintained by the LLM itself. The institution is the source of truth; the agent is read-only. This is the right specialisation for a high-stakes, single-institution advisor: the corpus is already curated, and the question is how to navigate it cleanly, not how to maintain it.
