#import "../diagrams.typ": system-arch, crawl-pipeline, wiki-layout, tool-surface, hybrid-retrieval, sse-lifecycle

= System Description

== Overview and design commitments

The LaSalle Wiki Tutor is structured as five sequential stages and one observability spine. The catalog is crawled into raw HTML, the raw HTML is rendered into a Markdown wiki with strict frontmatter, the wiki is wrapped by a read-only Python API that exposes ten tools, the tools are bound to a streaming agent that runs over Server-Sent Events, and the SSE stream feeds a React client served from the same FastAPI process. Three MongoDB collections record what happened. @fig:system-arch shows the shape.

#figure(system-arch, kind: image,
  caption: [System architecture. Five stages from crawl to client; one MongoDB store for observability and conversation history.],
) <fig:system-arch>

Four design commitments anchor the rest of this section. We extract structured records by targeting Drupal field selectors rather than running whole-page HTML-to-Markdown conversion. We bound the agent's view of the catalog to ten deterministic tools, with a system-prompt-enforced budget of at most five tool calls per response. We confine vector retrieval to one tool. We record per-turn reasoning passages and tool timings on the side, never on the SSE hot path, so the evaluation in Section 5 has measured ground truth.

== Crawl and corpus construction

The source corpus is the bilingual academic catalog at `salleurl.edu`, a Drupal-based site that publishes one URL per program in each language plus a hierarchy of per-program subpages (goals, requirements, curriculum, methodology, faculty, careers). The site does not publish a sitemap; the published `robots.txt` requests a 10-second crawl delay. The crawler in `scripts/fetch_catalog.py` walks the program index in three phases (enumerate seeds, fetch programs and subjects, verify integrity), is resumable across interruption, and honours the requested delay. We measure 179 English program records and 178 Spanish program records (357 total programs), with 2,314 English and 2,292 Spanish subject records (4,606 subjects in total); these counts are computed directly from `wiki/meta/catalog.jsonl` and `wiki/meta/subjects.jsonl` rather than from the build-summary file `wiki/meta/stats.md`, which is a downstream artefact. @fig:crawl-pipeline traces the three crawl phases and the field-targeted extraction step that hands off to the pairing stage described below.

#figure(crawl-pipeline, kind: image,
  caption: [The crawl-and-build pipeline. Field-targeted extraction produces structured JSONL; cross-language pairing runs greedy bipartite matching over four signals.],
) <fig:crawl-pipeline>

Cross-language pairing assigns each English program record an `equivalent_program_id` pointing to its Spanish counterpart (and vice versa) where one exists. The matcher in `scripts/build_wiki.py` scores every EN--ES pair on four signals (slug similarity, title similarity, shared subject URLs, and a structural-attribute match over ECTS, duration, and modality), combined with weights 0.20, 0.20, 0.45, and 0.15 respectively. A pair is auto-linked when the weighted score exceeds 0.30, OR when shared subjects and structural match both clear 0.5, OR when title and slug similarity jointly clear permissive thresholds, OR when title and structural agreement are both very high. Matching is greedy bipartite: each Spanish program can be claimed only once. We measure 103 auto-linked pairs out of 179 English programs, a link-coverage rate of 57.5%. The remaining 76 unlinked English programs cluster heavily in short-format levels, computed against the English-side counts as the denominator: 28 of 49 specialisations (57%), 27 of 36 "other" entries (75%), and 8 of 25 online courses (32%) remain unlinked. By contrast, only 1 of 29 English bachelors and 11 of 38 English masters are unlinked, so the major degree types are captured well and the unlinked tail corresponds largely to short courses where genuine single-language existence is common. The `pairing_confidence` field stored in the frontmatter is the weighted-score signal, not a probability of correctness; the OR-rules deliberately allow correct pairs with low scores through. Section 5.1 reports the rule-fired decomposition, which shows that 45% of auto-linked pairs sit in the 0.30--0.50 weighted-score band and would have been missed by a single-threshold approach.

== Field-targeted extraction and the wiki schema

The wiki render step takes the raw HTML and produces structured records, not Markdown blobs. For each program subpage the extractor looks for Drupal field classes (`field-name-overview`, `field-name-careers`, and so on) and runs `markdownify` only on the inner HTML of each named field. This avoids the noise that whole-page HTML-to-Markdown produces -- navigation chrome, breadcrumbs, footer boilerplate, and cookie banners -- which would otherwise inflate field sizes and pollute the downstream retrieval body. A field that fails to extract triggers a tracked fallback path so corpus health is monitorable. We measure a fallback rate of 1.6%, comfortably below the 5% target we set for ourselves.

#figure(wiki-layout, kind: image,
  caption: [On-disk wiki layout and program frontmatter schema. Each program is a directory of Markdown files with YAML frontmatter; each subject is a single Markdown file. Sidecars in `meta/` carry the full frontmatter dump, EN--ES pairings, and the static-embedding `.npz` matrices.],
) <fig:wiki-layout>

The wiki layout mirrors the catalog's natural hierarchy. @fig:wiki-layout lays out the directory tree alongside the program frontmatter schema. Frontmatter fields are populated at the following measured rates: eighteen fields (`title`, `slug`, `canonical_program_id`, `level`, `area`, `modality`, `duration`, `languages_of_instruction`, `schedule`, `location`, `start_date`, `tuition_status`, `admissions_contact`, `official_name`, `source_url`, `source_fetched_at`, `extractor_version`, and `official`) are present in 100% of records; `ects` is present in 95.5%, `subject_count` in 86.6%, `tags` in 59.4%, `equivalent_program_id` and `pairing_confidence` in 57.7% (the same population as the auto-linked pairs by construction), and `degree_issuer` in 49.9%. The completeness ratios that matter for retrieval (the lexical-search fields and the language-and-level facets) are at or above 86%.

== The ten-tool surface

The agent reaches the wiki through ten tools, each a Python coroutine wrapping a function in `catalog_wiki_api`. The tools fall into three families. The browsing family covers the cases where the student is exploring: `search_programs` for free-text queries, `list_programs` for filtered structured browse, `get_index_facets` for the area-and-level inventory, `compare_programs` for side-by-side comparisons. The detail family covers focused look-ups: `get_program`, `get_program_section`, `get_curriculum`, `get_subject`. The routing family covers meta questions where the catalog itself contains the answer: `get_faq` and `get_glossary_entry`. The system prompt tells the agent to spend at most five tool calls per response and to prefer the cheapest tool that resolves the student's question; the tools themselves return structured JSON with explicit `ok` and `error` fields so the model can recover from a missing argument or a not-found id without escalating. @fig:tool-surface lays out the ten tools by family.

#figure(tool-surface, kind: image,
  caption: [The ten-tool surface, grouped by family. Blue tiles are retrieval and detail tools; green tiles are the routing tools that answer meta questions directly from the catalog. Two example call sequences the agent typically takes: an explorer follows `get_index_facets` → `list_programs` → `get_program`, and a comparison shopper follows `search_programs` → `compare_programs` → `get_curriculum`.],
) <fig:tool-surface>

Every tool wraps its public API call in an argument-coercion layer that the agent's strict-mode tool-calling occasionally needs. Optional string filters are normalised so the literal empty string becomes a missing filter, and required string arguments that arrive empty return a structured `missing_argument` error with a hint telling the model which sibling tool to call to obtain a usable value. This pattern -- normalise where the model is permissive, return a structured hint where the model is wrong -- keeps the tool surface forgiving without softening the API contract.

== Hybrid retrieval inside #raw("search_programs")

`search_programs` is the only tool in which vector retrieval lives. Its job is to take a free-text query and return a ranked list of programs from one of the language catalogs. The retrieval pipeline computes two scoring branches that are then blended: a lexical branch and a semantic branch. Each branch is pool-normalised into the closed interval [0, 1] over the candidate pool, the two are combined linearly with weights 0.55 and 0.45, and a small intent prior is multiplied in last that nudges substantive degree-level programs up and short-format courses down when the query carries cues like "bachelor", "master", or "doctorate" and their Spanish equivalents. @fig:hybrid-retrieval traces the full data flow from query to ranked top-k.

#figure(hybrid-retrieval, kind: image,
  caption: [Hybrid retrieval inside `search_programs`. BM25-F is the lexical pole; Model2Vec is the semantic pole; both branches are pool-normalised before the linear blend and a small intent prior is multiplied in last.],
) <fig:hybrid-retrieval>

The lexical pole is BM25-F with six fields (title 4.0, tags 3.0, area 2.0, level 1.5, body 1.0, slug 0.5), a Robertson--Spärck-Jones IDF @sparck1972idf, and the standard BM25 hyperparameters $k_1 = 1.5$ and $b = 0.75$ @robertson2009bm25. Queries pass through a synonym-expansion table before scoring (so "hacking" expands to include "cybersecurity"; "aprendizaje automático" expands to "machine learning"). The semantic pole uses Model2Vec's `minishlab/potion-base-8M` model @tulkens2024model2vec, a static distilled embedding family that produces fixed-size 256-dimensional vectors per program without a transformer encoder pass at query time, in the family characterised by recent peer-reviewed work on static sentence representations @wada2025staticembeddings. The embeddings are pre-built once at wiki-render time and stored as L2-normalised `numpy` arrays in `wiki/meta/embeddings_en.npz` and `wiki/meta/embeddings_es.npz`; query embedding takes a few milliseconds, cosine similarity is a single matrix-vector multiply, and the whole pipeline serves from a `t3.micro` with no specialised infrastructure.

Both signal streams are normalised within the candidate pool before blending, not against absolute corpus statistics. This is the right choice for a 357-program catalog: a query that produces a single near-perfect lexical hit and three weak ones should not have its lexical score crushed against the semantic distribution, and vice versa. The blend weights 0.55 lexical and 0.45 semantic were chosen empirically against a development benchmark; the value of the lexical bias for a frontmatter-heavy catalog is visible in the ablation reported in Section 5.2. The `LASALLE_RANKER_MODE` environment variable selects among `hybrid`, `lexical` (BM25-only), `semantic` (cosine-only), and `token_overlap` (the legacy baseline retained for regression comparison). The same environment variable feeds the four-mode ablation reported below.

== Streaming agent runtime and observability

The agent itself is a thin wrapper over Agno's `Agent` class, configured to use OpenAI's Responses API with `gpt-5.4` at medium reasoning effort. The agent maintains eight most-recent runs of conversation history via Agno's `num_history_runs=8`, with MongoDB session persistence backed by the `wiki_tutor_agent_sessions` collection. Token budgets and tool-call budgets are enforced at the prompt level rather than via API parameters: the system prompt explicitly tells the model to stop at five tool calls per turn unless an honest answer truly requires more, and the empirical median over the production trace store is well below this limit (Section 5.3).

#figure(sse-lifecycle, kind: image,
  caption: [SSE event lifecycle and observability fan-out. The `BaseSSEAdapter` is in the hot path; the `TurnTraceRecorder` is a parallel listener that writes one document per `run_id` to the trace collection.],
) <fig:sse-lifecycle>

@fig:sse-lifecycle shows the streaming hot path and the parallel observability listener. Events flow over Server-Sent Events between the agent and the client. The vocabulary covers session lifecycle (`session.started`, `session.ended`), reasoning (`agent.thinking.start`, `agent.thinking.delta`, `agent.thinking.end`), tool execution (`tool.start`, `tool.end`), and the final response (`final_response.delta`, `final_response.end`, `response.final`). The wire format wraps each event in an envelope that carries the event name, timestamp, elapsed milliseconds, correlation id, and agent metadata; the payload sits under a `data` field. The client's React reducer is structured so that delta events update only the rendered text; non-delta events transition the turn through a small state machine. The system supports cooperative cancellation through a process-local registry that pairs each in-flight `query_id` with an `asyncio.Event` the agent loop polls between tool calls.

Observability is the spine that makes the rest of the paper measurable. Three MongoDB collections cooperate without coupling. The `wiki_tutor_agent_sessions` collection is Agno's own session record, which we treat as read-only and join against on demand. The `wiki_tutor_conversations_meta` collection is the application's title-and-language sidecar, with a `version` field that gives the rename endpoint optimistic-concurrency semantics and a `deleted_at` field that supports soft delete. The `wiki_tutor_turn_traces` collection is the empirical workhorse: one document per `run_id`, populated by a `TurnTraceRecorder` that listens on the same event manager as the SSE adapter but writes only on turn completion, so it never sits on the streaming hot path. Each trace document carries every reasoning passage with timestamps, every tool invocation with arguments preview and duration, the language, the user id, the start and end of the turn. This is what we read in Section 5.3 to report per-tool latency without instrumenting the production code.

The agent's system prompt also enforces a scope boundary. The agent is instructed to answer in-scope questions about the LaSalle catalog (program details, comparisons, curricula, careers, FAQ-style routing) and to decline politely, in the user's language, when the question is out of scope (other universities, general knowledge, coding help, personal or visa advice, writing on the student's behalf). The prompt explicitly forbids fabrication when the catalog is silent; tuition is the canonical example, with the agent instructed to route the student to the admissions URL rather than invent a price. The prompt also instructs the model to refuse role-swap and system-prompt-disclosure attempts. Section 5.5 reports a small spot-check of these guardrails on the live deployment.
