= Discussion

== When tools-over-wiki beats chunk-and-embed

The evidence in Section 5 lets us be more precise about the regime in which a compiled wiki and a small tool surface dominate a chunk-and-embed retrieval pipeline. The conditions that hold for the LaSalle catalog are: the corpus is #emph[bounded] (under a thousand top-level records), #emph[structured] (each record has rich frontmatter that the retriever can exploit), #emph[slowly changing] (a typical institutional catalog turns over annually), and #emph[frontmatter-heavy] (the discriminative signal lives in title, area, level, and tags more than in body prose). These conditions invert the assumptions a chunk-and-embed pipeline is optimised for. A chunking pipeline pays its cost up front to handle unbounded, unstructured, fast-changing prose where the discriminative signal is buried in body text -- a use case the LaSalle catalog does not present. We are not arguing that chunk-and-embed is wrong everywhere; we are arguing that it is the wrong default for catalog-shaped knowledge.

The deeper point sits with the retrieval surface. A vector database forces the agent to navigate the corpus through similarity, an abstraction that obscures the structural relationships the catalog already publishes (a program has a curriculum, a curriculum has years, a year has subjects). The ten-tool surface preserves those relationships explicitly: `get_curriculum` returns the curriculum as a year-keyed structure, not as the most-similar passage to a query. The model can navigate the catalog the way a human advisor does, by querying its facets, drilling into a program, comparing two programs side-by-side, fetching one course's detail. The retrieval-as-tool framing makes the structural knowledge usable by the model; the chunking abstraction destroys it.

== Where vector retrieval does earn its place

We have argued against vector retrieval as the agent's general substrate, not against vector retrieval as a primitive. Inside `search_programs` the semantic branch carries its weight: the ablation in Section 5.2 shows that the hybrid blend is the only mode reaching 100% top-5 coverage, and the marginal gain at top-5 over lexical-only (90% to 100%) comes entirely from the semantic branch catching queries where literal-token overlap fails -- "hacking" mapping to "Cybersecurity", "aprendizaje automático" mapping to "Artificial Intelligence". This is the case for keeping the dense signal: it costs almost nothing at our scale (a 180 kB sidecar per language, a numpy matmul per query, a few milliseconds of `gpt-5.4`-comparable latency), and it removes a class of retrieval miss that would otherwise drop the system to the lexical mode's 90% top-5 ceiling.

The cost contrast against a full RAG pipeline is worth naming directly. Running this system requires a `t3.micro` and `mongo:6.0` in a container. There is no managed vector database to provision, no index lifecycle to maintain, no chunking strategy to tune, no embedding-drift detector to wire up. The retrieval ablation in Section 5.2 was a Python script that ran in under a minute and produced the data behind @fig:ablation. The per-conversation cost reported in Section 5.4 is dominated by `gpt-5.4` tokens, not by retrieval infrastructure. This is what the case for tools-over-wiki looks like in numbers: the operational tax that RAG-by-default imposes is paid by every catalog-shaped application that defaults to it.

== Limitations and threats to validity

We name five. First, the 57.5% link-coverage rate on cross-language pairing is below the 90% target the project documentation originally set, even after the OR-rule decomposition makes clear that 45% of auto-linked pairs would be missed by a single-threshold approach. The unlinked tail is in specialisation and short-format courses where genuine single-language existence is common, but we have not run a manual ground-truth review to separate "genuinely single-language" from "matcher miss". A future iteration would either confirm the unlinked population is largely single-language by inspection or close the gap with a manual review pass.

Second, the refusal-correctness evidence in Section 5.5 is a hand-curated qualitative spot-check of sixteen queries against the live deployment. We have not run a systematic adversarial-prompt benchmark and we do not claim refusal-rate guarantees at scale. The system did honour its scope on every query in the test set, and the refusals are direct and offered an in-scope alternative, but this is a sanity check, not a study.

Third, the evidence base is single-institution. The LaSalle catalog is one Drupal-rendered Spanish university catalog; generalising the field-targeted extractor to a different CMS, or to an institution that publishes its catalog as PDFs, would re-open the extractor work. The corpus shape we argue for (bounded, structured, slowly changing, frontmatter-heavy) is widely instantiated across higher education and adjacent verticals, but we have not demonstrated transfer.

Fourth, the latency measurements in Section 5.3 come from a production trace store with only eighteen turn traces and sixty-two tool calls. The distributions are real but the sample size is small; the upper-percentile estimates should be read as upper bounds for a system that has not yet seen heavy load.

Fifth, the design rests on a deterministic-extractor assumption: the Drupal field selectors that the extractor targets are stable. A CMS migration on the institution's side would force a re-tuning of the extractor and a re-render of the wiki. The fallback rate of 1.6% measures how often this assumption held on the current crawl; a higher fallback rate after a future re-crawl would be a leading indicator of CMS drift.
